### ISSUE TITLE
examples fail to build with boost 1.83+

### ISSUE THREAD

**Issue by efferre79** [orocos/orocos_kinematics_dynamics#462]
The boost API changed with boost 1.80+, see also [here](https://www.boost.org/doc/libs/1_80_0/libs/timer/doc/index.html)

```
FAILED: examples/CMakeFiles/chainiksolverpos_lma_demo.dir/chainiksolverpos_lma_demo.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++  -I/usr/include/eigen3 -I/var/tmp/portage/sci-libs/orocos_kdl-1.5.1/work/orocos_kinematics_dynamics-1.5.1/orocos_kdl/src -I/var/tmp/portage/sci-libs/orocos_kdl-1.5.1/work/orocos_kinematics_dynamics-1.5.1/orocos_kdl/models -I/var/tmp/portage/sci-libs/orocos_kdl-1.5.1/work/orocos_kdl-1.5.1_build/src  -O2 -pipe -march=znver3 -ggdb -MD -MT examples/CMakeFiles/chainiksolverpos_lma_demo.dir/chainiksolverpos_lma_demo.cpp.o -MF examples/CMakeFiles/chainiksolverpos_lma_demo.dir/chainiksolverpos_lma_demo.cpp.o.d -o examples/CMakeFiles/chainiksolverpos_lma_demo.dir/chainiksolverpos_lma_demo.cpp.o -c /var/tmp/portage/sci-libs/orocos_kdl-1.5.1/work/orocos_kinematics_dynamics-1.5.1/orocos_kdl/examples/chainiksolverpos_lma_demo.cpp
In file included from /var/tmp/portage/sci-libs/orocos_kdl-1.5.1/work/orocos_kinematics_dynamics-1.5.1/orocos_kdl/examples/chainiksolverpos_lma_demo.cpp:59:
/usr/include/boost/timer.hpp:21:3: error: #error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
   21 | # error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
      |   ^~~~~
In file included from /usr/include/boost/config/header_deprecated.hpp:18,
                 from /usr/include/boost/timer.hpp:24:
/usr/include/boost/timer.hpp:25:1: note: ‘#pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.’
   25 | BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
      | ^~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by MatthijsBurgh** [comment]
Feel free to open a PR, which is compatible with the older and newer versions of Boost. I don't have time to fix this, this month.
